version: '3.8'

services:
  meyers-api:
    build: ..
    ports:
      - "5015:5015"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=5015
      - DEBUG_MODE=False
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5015/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 